// Code generated by oto; DO NOT EDIT.

'use strict';

 
class GreeterService {
	
	async greet(greetRequest) {
		const headers = {
			'Accept':		'application/json',
			'Accept-Encoding':	'gzip',
			'Content-Type':		'application/json',
		}
		greetRequest = greetRequest || {}
		const response = await fetch('/oto/GreeterService.Greet', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(greetRequest)
		})
		const text = await response.text()
		let json = null
		if (text) {
			try {
				json = JSON.parse(text)
			} catch (e) {
				if (!response.ok) {
					throw new Error(`GreeterService.Greet: ${response.status} ${response.statusText}`)
				}
				throw e
			}
		}
		if (!response.ok) {
			if (json && json.error) {
				throw new Error(json.error)
			}
			throw new Error(`GreeterService.Greet: ${response.status} ${response.statusText}`)
		}
		return json || {}
	}
	
}

