// Code generated by oto runtime; DO NOT EDIT.

export function createClient(basepath = "/") {
	return {
		States: {
			async getByCode(pathParams, options) {
				const headers = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/lookup/states/{code}"
				if (!pathParams) {
					throw new Error("pathParams is required")
				}
				url = url.replace("{code}", encodeURIComponent(String(pathParams.code)))
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					if (json && json.error) {
						throw new Error(json.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json || {}
			},
			async getMany(options) {
				const headers = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/api/v1/lookup/states/"
				const response = await fetch(url, {
					method: "GET",
					headers,
				})
				const text = await response.text()
				let json = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new Error(response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					if (json && json.error) {
						throw new Error(json.error)
					}
					throw new Error(response.status + " " + response.statusText)
				}
				return json || {}
			},
		},
	}
}
